Server:
 RunMode: debug
 HttpPort: 8888
 ReadTimeout: 60
 WriteTimeout: 60
App:
 DefaultPageSize: 10
 MaxPageSize: 100
 LogSavePath: storage/logs
 LogFileName: app
 LogFileExt: .log
 UploadSavePath: storage/uploads
 UploadServerUrl: http://127.0.0.1:8888/static #上传文件后的用于展示的文件服务地址
 UploadImageMaxSize: 5 #5M
 UploadImageAllowExts: 
 - .jpg
 - .png
 - .jpeg
Database:
 DBType: mysql
 Username: root
 Password:
 Host: 127.0.0.1:3306
 DBName: go
 TablePrefix: blog_
 Charset: utf8
 ParseTime: True
 MaxIdleConns: 10
 MaxOpenConns: 30
JWT:
 Secret: eddycjy
 Issuer: blog-service
 Expire: 7200